### ISSUE TITLE
A community project

### ISSUE THREAD

**Issue by codefriar** [PetriPod/PetriPod#1]
I want this to be a truly community project. To the point that I think we should start by doing a couple of housekeeping things. I propose that we: 

1. Establish 'rules' - when and how people become maintainers, vs. developers etc. 
2. We should discuss the project name. I chose Petri-Dish / Petri but only because I had to give it a name to start. I'm not tied to the name, so lets come to consensus on one!

**Comment by ghost** [comment]
Project Names (suggestions):
Podworks - pods that just work
PetriPods - services don't grow in a dish
CulturePod - services grow with CulturePod
Enzymany - this name just sound cool, but not as cool as deploying yourself!
ServicePods - Services in a pod
uDeploy - deployed by you, today
DeployPod - it's all you
Deployable - life, deployable
DeployLife - your life, deployed
Cultivate - set and grow

**Comment by kpoppel** [comment]
PetriLab is not reserved as an organisation name.

**Comment by denis-ev** [comment]
> PetriLab is not reserved as an organisation name.

Yeah, but Petrilab.com is for sale for $3195. I personally would like a matching domain.

**Comment by ghost** [comment]
and PetriLab is too close to HomelabOS..

we aren't trying to rip the project. it's a separate entity

enzymany.com, .net, and .org are available

**Comment by kpoppel** [comment]
I like Petri.. More ideas could be Cluster@home, PetriPod.

**Comment by denis-ev** [comment]
I like Cluster@Home 👍

**Comment by ghost** [comment]
Still to close to home labs..

Besides, people deploy this to digital ocean and the likes... That's not at home..

And yea, I liked my idea of PetriPod/s. Was one of the better ones, I guess.

What does @codefriar think?

**Comment by ghost** [comment]
Petripod.com, .net and .org are available
Petripods.com, .net, and .orgare all available too

**Comment by ghost** [comment]
Sent this via email but it didn't come through for some reason:

I'm also a fan but `clusterathome.com` is a bit long and there is not a great way to shorten it, like HomelabOS shortens nicely to hlos. I also like PetriPod. Cultivate sounds nice but doesn't tell you anything about the project like cluster@home does well and petripod does to a point.

**Comment by ghost** [comment]
> Sent this via email but it didn't come through for some reason:
> 
> I'm also a fan but `clusterathome.com` is a bit long and there is not a great way to shorten it, like HomelabOS shortens nicely to hlos. I also like PetriPod. Cultivate sounds nice but doesn't tell you anything about the project like cluster@home does well and petripod does to a point.

Valid points, but the name doesn't have to necessarily tell anyone about the product... For instance.. Monica, a PRM named after the creators favourite friends character.. Mastodon, named after the creators favourite band.. Microsoft Azure, named because the primary colour during development was blue...

**Comment by ghost** [comment]
You're right. All three names are fine

**Comment by ghost** [comment]
When I thought of cultivate, I figured that if the project really got some momentum, it would be easier than the others to be used as a verb..

"Hey man, did you check out that new app I made to connect amputee pet owners with other amputee pet owners?"

"Nah bro, sick idea, but ain't nobody got time for that"

"It's all good bro, I cultivated it.. now my mum and her wheelie walking group use it"

"Sweet as bro" 

••clacks on a keyboard for 2 minutes••

"Now I've got 5 nodes ready to use.. thanks Cultivate"

..  just a thought..

Lets put a vote to it.

Put your first three preferences (and/or suggestions) in this thread and we will tally.

@codefriar 
@denis-ev 
@evanmn 
@kpoppel

**Comment by kpoppel** [comment]
My votes go to:
- PetriPod(s)
- Kunic or Kunicl (just to throw in an amalgation of Kube, unique, Network (NIC), Unix, Cluster)

**Comment by codefriar** [comment]
I think my votes go to:

* PetriPod (petripod.com)
* Petri-dish (petri-dish.io)

**Comment by ghost** [comment]
I'd vote:
* PetriPod/s
* Cluster@Home

Cluster@Home doesn't necessarily mean at your house, it can just mean you don't need a datacenter and team around you to get it set up.

**Comment by ghost** [comment]
That's a good point, @evanmn.

But, majority rules.

Looks like it's PetriPod, @codefriar. Let's get this party started

Good work team

**Comment by codefriar** [comment]
Ok team, one last question here,

I just discovered we can get petripods.dev, if we're inclined. Thoughts?

**Comment by codefriar** [comment]
https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/renaming-an-organization

I am renaming the Org as PetriPods.

**Comment by ghost** [comment]
I like .com
 What's everyone else think?
@denis-ev 
@evanmn 
@kpoppel

**Comment by ghost** [comment]
I'd be fine with either, although it would be better to get petripod.tld instead of petripods.tld because that is our organization name.

**Comment by kpoppel** [comment]
I have no preferences :-)

**Comment by ghost** [comment]
Denis voted .dev via private message with me.
For the sake of it being known, via issue.

It's assumed that @codefriar prefers the .Dev over.com

So the decision rests with .dev

**Comment by codefriar** [comment]
I have purchased PetriPod.dev via google DNS. Closing this issue, opening a new one for further governance discussion
