### ISSUE TITLE
Nominations for first service?

### ISSUE THREAD

**Issue by codefriar** [PetriPod/PetriPod#4]
Team, 

I figure it makes sense for us all to work on a common goal, at least initially. To that end, @evanmn and @kpoppel have done some great pioneering work on getting k3s, and traefik2 up and running. While I won't claim to perfectly understand everything, I should have it automated later today (eastern us). So lets talk about what we might want as our first 'service' that  is deployable to our established platform.

I think, just for comforts sake, something like portainer would be my choice - but that's because I'm comfortable with using and testing Portainer to make sure it works as expected. 

I think hlos started with organizr though. 

Thoughts?

**Comment by ghost** [comment]
Votes seem to be effective here,

I'll start, by saying Portainer is ok with me.

I would vote a dashboard to be first service, but I'm not sure SUI works with k3s deployments, and that's my preference (SUI, heimdall, then organizr)

Place your votes team

**Comment by ghost** [comment]
I also like SUI and have not tried heimdall. I don't see why sui would not work under k3s because it dosen't call docker or anything. Everything is just under static reading json files.

I'd be fine starting with portainer.

**Comment by codefriar** [comment]
Evan,

Actually the SUI shipped with Homelab is dynamic, it inspects the docker socket and lists services it finds.

**Comment by ghost** [comment]
Nevermind. Well if we were to ship SUI, we could either modify it to work with kubernetes or go with [this one](https://github.com/jeroenpardon/sui) that is configured with json files.

**Comment by codefriar** [comment]
Agreed. Since it’s written in PHP, we can call out to shell for kubectl get pods —all-namespaces and with json return to parse … I don’t see it as being too big a refactor when we get there.

**Comment by denis-ev** [comment]
Well SUI uses the Traefik API to get the information, as long as we are using traefik it will still work.

**Comment by kpoppel** [comment]
I am more a Heimdall type of person, but SUI is simple and neat that it picks up Traefik services automatically.
But, for the first service I'd go for Portainer too. It is an enabler for testing out things fast, before attempting to helm-chart it.

**Comment by codefriar** [comment]
Seems like we’re building a consensus around portainer?

**Comment by ghost** [comment]
It does seem that way.

Portainer sounds good

**Comment by codefriar** [comment]
Closing, with a consensus on Portainer
