### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by codefriar** [PetriPod/PetriPod#7]
Team, 

One of the reasons I love github is the brilliant github pages feature. It can bootstrap a website for us, with any Jekyll theme. Anyone have a preference as to the theme?

Ps: Not now, but when we're ready, there's an amazing plugin that will pull in the Wiki pages. And since the wiki pages are stored in a git repo attached to this one, we can automatically update the website whenever a wiki page is updated/edited.

**Comment by ghost** [comment]
Love it.

I'll check out some Jekyll themes soon

EDIT:
http://jekyllthemes.org/themes/edition/ (simple, effective, searchable)
http://jekyllthemes.org/themes/cc-urban/ ('bloggy', but nice. Not sure hows docs will fit into this)
http://jekyllthemes.org/themes/safarnama/ (nice dark theme..)
https://jekyllthemes.io/theme/just-the-docs (docs focused, may not be 'website' friendly)
http://jekyllthemes.org/themes/jasper2/ (reminiscent of Ghost)
http://jekyllthemes.org/themes/documentation-theme-jekyll/ (another docs centric theme, might be nice with some colour changes)
http://jekyllthemes.org/themes/hyde/ (Hyde seems to be very popular)
https://jekyllthemes.io/theme/carte (interesting one)

**Comment by denis-ev** [comment]
I like this one [Edition](http://jekyllthemes.org/themes/edition/)

**Comment by ghost** [comment]
Any votes on this one? Not sure how the docs are going to work, but I'll try

https://ndrewtl.github.io/airspace-jekyll/

**Comment by codefriar** [comment]
I actually kind of like this one: https://jekyllthemes.io/theme/doks-documentation-jekyll-theme found it by accident looking through the others.

**Comment by kpoppel** [comment]
I like a theme which keeps the navigation top line or sidebar visible at all times so getting around is made easy.
If the style is a single-page look, of course that does not matter, I just think that type is better suited for sales-sites.

Proposal:
http://jekyllthemes.org/themes/matjek/
http://jekyllthemes.org/themes/herringcove-theme/ (looks like to can do it too, but less industrial looks)
+1 on http://jekyllthemes.org/themes/documentation-theme-jekyll/

Edition is really nice - the matjek looks similar to Edition, and keeps the sidebar in place too.

**Comment by codefriar** [comment]
I kinda like matjek. I really like Edition. I think a quick css fix to the sidebar in edition could keep it in place. 

Maybe Edition with Matjek colors? and a fixed sidebar?

**Comment by denis-ev** [comment]
Sounds good to me.

**Comment by ghost** [comment]
All of these look good and I trust your decision. I will be on mobile for the next couple of days, so won't be able to work on much of anything.

**Comment by ghost** [comment]
Sounds like the consensus is 'edition' theme with 'Matjek' theme colours.

Good work team. Closing this issue
