### ISSUE TITLE
Code of Conduct Acceptance

### ISSUE THREAD

**Issue by ghost** [PetriPod/PetriPod#8]
The previous issue still has some discussion required, and should be closed once the CoC and CG documents are finalised (for the foreseeable future)

This issue is, specifically, for acceptance of the Code of Conduct.

Replying to this thread, denotes your acceptance of the Code of Conduct, pertaining to the version written prior to the accepted date. This means that, if the document is updated, community leaders will need to 're-accept' to update, and keep their community leader status.

Of course, if you no longer want to be a community leader, decline the Code of Conduct by comment on this issue, and request the 'contact us' page be updated by another community leader.

**Comment by codefriar** [comment]
@codefriar Agrees to the code of conduct.

**Comment by kpoppel** [comment]
@kpoppel Agrees to the code of conduct.

**Comment by ghost** [comment]
@evanmn agrees with the code of conduct.

**Comment by denis-ev** [comment]
@denis-ev Agrees to the code of conduct.
